#version: ""
#name: "my_sexy_app"
services:
#  my_app:
#    image: node:12-alpine
#    ports:
#      - 3000:3000
#    working_dir: /app
#    volumes:
#      - ./:/app
#    environment:
#      COMPOSE_PROJECT_NAME:
#      MYSQL_USER: root
#      MYSQL_PASSWORD: secret
#      MYSQL_DB: todos
#      MYSQL_HOST: mysql
#    secrets:
#      - mysql_root_pass
#    command: >
#      sh -c "set
#      && echo Im running ${COMPOSE_PROJECT_NAME}
#      && yarn install && yarn run dev"
#
  psql:
    image: postgres:14.4
    volumes:
       - ./db/init:/docker-entrypoint-initdb.d
       - psql_volume:/var/lib/postgresql/data
    environment:
#      COMPOSE_PROJECT_NAME:
      POSTGRES_DB: "yandex_open_lect"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_root_pass
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: #for changing standard 5432 port to, check .env
    ports:
      - ${PGPORT}:${PGPORT}
    secrets:
      - psql_root_pass
#    command: >
#      sh -c "set"

secrets:
  psql_root_pass:
    file: ./secrets/psql/root_pass

volumes:
  psql_volume: