#version: ""
#name: "my_sexy_app"
services:
#  my_app:
#    image: node:12-alpine
#    ports:
#      - 3000:3000
#    working_dir: /app
#    volumes:
#      - ./:/app
#    environment:
#      COMPOSE_PROJECT_NAME:
#      MYSQL_USER: root
#      MYSQL_PASSWORD: secret
#      MYSQL_DB: todos
#      MYSQL_HOST: mysql
#    secrets:
#      - mysql_root_pass
#    command: >
#      sh -c "set
#      && echo Im running ${COMPOSE_PROJECT_NAME}
#      && yarn install && yarn run dev"
#
  psql:
    image: postgres:14.4
    volumes:
#      - todo-mysql-data:/var/lib/mysql
    environment:
#      COMPOSE_PROJECT_NAME:
#      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_DATABASE: todos
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    secrets:
      - psql_root_pass
    command: > 
#      sh -c "set"

volumes:
  todo-mysql-data:

secrets:
  psql_root_pass:
    file: ./secrets/mysql/mysql.txt